CREATE DATABASE DevConnectITS;

USE DevConnectITS;

CREATE TABLE usuarios
(
    id_user INT  UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(80) NOT NULL,
    email VARCHAR(150)  NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
